title: La magnétique
theme: minima
url: "https://la-magnetique.fr" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-paginate 
  - jekyll-redirect-from 
base-url: "la-magnetique"

whitelist:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "assets/**"
    values:
      sitemap: false
lang: fr
timezone: Europe/Paris
tagline: Laboratoire d'expérimentation et de création sonore sous forme d'ateliers
author: Florian Sauvaire, Achille Reig
social:
  links:
    - https://www.facebook.com/Lamagnetiqueasso
    - https://www.instagram.com/lamagnetique_/